version: "3"
services:

  api:
    image: api
    restart: always
    build: ./
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      DB_URL: mongodb://root:example@mongo:27017/
      JWT_SECRET: EXAMPLE

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
